// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Command = 3,
  Identifier = 4,
  Date = 5,
  Time = 6,
  ShortTime = 7,
  Number = 8,
  Tod = 9,
  LongTime = 10,
  Filter = 11,
  UnitFilter = 12,
  Range = 13,
  TimeRange = 14,
  DateRange = 15,
  Operator = 16,
  Note = 17
